import {GAME_ID, ESC_TRIVIA_LIVE} from "Common/constants";

const ACTION_PHASE_CHANGED = ESC_TRIVIA_LIVE + ":PHASE_CHANGED";
const ACTION_ROUTE_TO_GET_READY = ESC_TRIVIA_LIVE + ":ROUTE_TO_GET_READY";
const ACTION_RECORD_ANSWER = ESC_TRIVIA_LIVE + ":RECORD_ANSWER";

export {
	ACTION_PHASE_CHANGED,
	ACTION_ROUTE_TO_GET_READY,
	ACTION_RECORD_ANSWER,
};
